# Generated by Django 3.2.9 on 2021-11-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pokemon1', models.IntegerField()),
                ('pokemon2', models.IntegerField()),
                ('pokemon3', models.IntegerField()),
                ('pokemon4', models.IntegerField()),
                ('pokemon5', models.IntegerField()),
            ],
        ),
    ]
